### ISSUE TITLE
Production build error

### ISSUE THREAD

**Issue by BartosStore** [vasturiano/kapsule#5]
Hi,

  thanks for kapsule! I use kapsule/react-kapsule to integrate timeline-chart into react application. 
  
  I am happy with this combination but when I need to publish my project this error occurs:

```
TypeScript error in C:/dev/cs/condition_monitoring/condition_monitoring/Frontend/node_modules/kapsule/dist/kapsule.d.ts(39,3):
Property 'resetProps' of type '(() => KapsuleInstance) | undefined' is not assignable to string index type 'PropGetter | PropSetter | KapsuleMethod'.  TS2411
```

```
    37 | interface KapsuleInstance {
    38 |   (constructorItem: any): KapsuleInstance;
  > 39 |   resetProps?(): KapsuleInstance;
       |   ^
    40 |   [propOrMethod: string]: PropGetter | PropSetter | KapsuleMethod;
    41 | }
    42 |
```

  Could you help me? Do you know where can be problem?

**Comment by vasturiano** [comment]
Thanks for the report @BartosStore.

I've updated the type definitions in this module which should solve your TS issue if you upgrade your dependency tree to the latest version of `kapsule`.
